version: '3.8'
services:
  frontend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
     - .:/usr/src/app/
    env_file:
     - .env
    ports:
      - "3100:3000"
volumes:
  ignore: